After this patch, the build of the CVS head should be succeed.
(Patch 1) "Closure.java" has been changed for test-suits:
          src/test/groovy/ClosureTest.groovy
          src/test/groovy/ClosureCurryTest.groovy
          src/test/groovy/ExpandoPropertyTest.groovy

(Patch 2) The method asArray() of "Invoker.java" has been enhanced.

Here are some error messages in building with the previous Closure.java (revision 1.48):
Testcase: testCurry(ClosureCurryTest):  Caused an ERROR
Incorrect arguments to closure:
ClosureCurryTest$_testCurry_closure1@182c132. Expected: [class
java.lang.Object, class java.lang.Object], actual: [there]
groovy.lang.IncorrectClosureArgumentsException: Incorrect arguments to
closure: ClosureCurryTest$_testCurry_closure1@182c132. Expected: [class
java.lang.Object, class java.lang.Object], actual: [there]

Testcase: testVariableLengthParameterList(ClosureTest): Caused an ERROR
Incorrect arguments to closure:
ClosureTest$_testVariableLengthParameterList_closure3@6e41b5. Expected:
[class [Ljava.lang.Object;], actual: [1, 2, 3]
groovy.lang.IncorrectClosureArgumentsException: Incorrect arguments to
closure: ClosureTest$_testVariableLengthParameterList_closure3@6e41b5.